In [1]:
import requests as r
from bs4 import BeautifulSoup as bs


# portfolioResponse = r.get("https://www.scrapethissite.com/pages/simple/")

# soup = bs(portfolioResponse.content,"html.parser")
# # print(soup.prettify())
# with open("ScrapeThisSiteResponse.html","w")as file:
#     file.write(str(soup))

/Users/ahmad/Documents/GitHubProjects/DataAnalysisClassJune2026/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [8]:
import pandas as pd
with open("ScrapeThisSiteResponse.html","r") as file:
    soup = bs(file.read(),"html.parser")
    # print(soup.find("title").text)
    countryNames = soup.find_all("h3",class_="country-name")
    countryCapitals= soup.find_all("span",class_="country-capital")
    countryPopulation= soup.find_all("span",class_="country-population")
    countryArea = soup.find_all("span",class_="country-area")
    "============================//=============================="
    CountryInfo  = {"Country Name": [] , "Country Capital" : [] , "Country Population" : [] , "Country Area" : [] }
    for i in range(0,len(countryNames)):
        CountryInfo["Country Name"].append(countryNames[i].text.strip())
        CountryInfo["Country Capital"].append(countryCapitals[i].text.strip())
        CountryInfo["Country Population"].append(countryPopulation[i].text.strip())
        CountryInfo["Country Area"].append(countryArea[i].text.strip())

    countryInfoDataFram = pd.DataFrame(CountryInfo)
    countryInfoDataFram.to_excel("CountryData.xlsx",index=False)

In [6]:
countryInfoDataFram

             Country Name   Country Capital Country Population Country Area
0                 Andorra  Andorra la Vella              84000        468.0
1    United Arab Emirates         Abu Dhabi            4975593      82880.0
2             Afghanistan             Kabul           29121286     647500.0
3     Antigua and Barbuda        St. John's              86754        443.0
4                Anguilla        The Valley              13254        102.0
..                    ...               ...                ...          ...
245                 Yemen             Sanaa           23495361     527970.0
246               Mayotte         Mamoudzou             159042        374.0
247          South Africa          Pretoria           49000000    1219912.0
248                Zambia            Lusaka           13460305     752614.0
249              Zimbabwe            Harare           11651858     390580.0

[250 rows x 4 columns]

In [3]:
import requests as r 
from bs4 import BeautifulSoup as bs



for i in range(1,25):
    re = r.get(f"https://www.scrapethissite.com/pages/forms/?page_num={i}")
    with open(f"scrapethissitePageNo{i}.html" ,"w") as file:
        soup = bs(re.content,"html.parser")
        file.write(str(soup.prettify()))

In [40]:
for i in range(1,25):
    with open(f"scrapethissitePageNo{i}.html" ,"r") as file:
        soup = bs(file.read()).prettify()
        # print(soup)

FileNotFoundError: [Errno 2] No such file or directory: 'scrapethissitePageNo1.html'

In [26]:
baseurl = "https://www.deckshop.pro"

re = r.get(f"{baseurl}/card/list")

soup = bs(re.content,"html.parser")

imagesUrl = soup.find_all("img",class_="card")

ImageUrlData = {"Name":[],"Url":[]}
for eachUrl in imagesUrl:
    # print(eachUrl)
    ImageUrlData["Name"].append(str(eachUrl.get("alt")).strip())
    ImageUrlData["Url"].append(str(eachUrl.get("src")).strip())

import pandas as pd

imagedf = pd.DataFrame(ImageUrlData)
imagedf

             Name                             Url
0       Skeletons   /img/card_ed_evo/Skellies.png
1      Ice Spirit  /img/card_ed_evo/IceSpirit.png
2          Bomber     /img/card_ed_evo/Bomber.png
3            Bats       /img/card_ed_evo/Bats.png
4             Zap        /img/card_ed_evo/Zap.png
..            ...                             ...
534  Mighty Miner    /img/card_ed/MightyMiner.png
535  Archer Queen    /img/card_ed/ArcherQueen.png
536   Goblinstein    /img/card_ed/Goblinstein.png
537          Monk           /img/card_ed/Monk.png
538   Boss Bandit     /img/card_ed/BossBandit.png

[539 rows x 2 columns]

In [22]:
imagedf

             Name                             Url
0       Skeletons   /img/card_ed_evo/Skellies.png
1      Ice Spirit  /img/card_ed_evo/IceSpirit.png
2          Bomber     /img/card_ed_evo/Bomber.png
3            Bats       /img/card_ed_evo/Bats.png
4             Zap        /img/card_ed_evo/Zap.png
..            ...                             ...
534  Mighty Miner    /img/card_ed/MightyMiner.png
535  Archer Queen    /img/card_ed/ArcherQueen.png
536   Goblinstein    /img/card_ed/Goblinstein.png
537          Monk           /img/card_ed/Monk.png
538   Boss Bandit     /img/card_ed/BossBandit.png

[539 rows x 2 columns]

In [39]:
# Scrapping Image
from tqdm import tqdm
for i in tqdm(range(len(ImageUrlData["Url"])),desc = "Downloading Image ... : "):
    imgUrl = ImageUrlData["Url"][i]
    re = r.get(f"{baseurl}{imgUrl}")
    imageName = ImageUrlData["Name"][i]
    with open(f"ScrappedImages/{imageName}.png","wb") as f:
        f.write(re.content)

Downloading Image ... :  40%|████      | 216/539 [00:36<00:53,  5.99it/s]

KeyboardInterrupt:

In [38]:
from tqdm import tqdm

# Scraping Images
for i in tqdm(range(len(ImageUrlData["Url"])), desc="Downloading Images"):
    imgUrl = ImageUrlData["Url"][i]
    re = r.get(f"{baseurl}{imgUrl}")
    imageName = ImageUrlData["Name"][i]
    with open(f"ScrappedImages/{imageName}.png", "wb") as f:
        f.write(re.content)

Downloading Images:  51%|█████     | 275/539 [01:57<01:52,  2.35it/s]

KeyboardInterrupt: